version: 0.0
os: linux

files:
  - source: /Project
    destination: /Project/app  # Adjust based on where you want to deploy your app.py

hooks:
  ApplicationStop:
    - location: stop_container.sh  # No 'scripts/' prefix since the file is in the root
      timeout: 300
      runas: root
  AfterInstall:
    - location: start_container.sh  # No 'scripts/' prefix since the file is in the root
      timeout: 300
      runas: root
