version: 0.0
os: linux

files:
  - source: /Project
    destination: /Project/app  

hooks:
  ApplicationStop:
    - location: stop_container.sh  
      timeout: 300
      runas: root
  AfterInstall:
    - location: start_container.sh  
      timeout: 300
      runas: root
